export const countries = [
  "México",
  "Estados Unidos",
  "Canadá",
  "Argentina",
  "Brasil",
  "Chile",
  "Colombia",
  "Perú",
  "Uruguay",
  "Paraguay",
  "Bolivia",
  "Ecuador",
  "Venezuela",
  "Costa Rica",
  "Panamá",
  "Guatemala",
  "Honduras",
  "El Salvador",
  "Nicaragua",
  "República Dominicana",
  "Cuba",
  "España",
  "Francia",
  "Alemania",
  "Italia",
  "Portugal",
  "Reino Unido",
  "Irlanda",
  "Países Bajos",
  "Bélgica",
  "Suiza",
  "Austria",
  "Suecia",
  "Noruega",
  "Dinamarca",
  "Finlandia",
  "Polonia",
  "República Checa",
  "Hungría",
  "Rumania",
  "Grecia",
  "Turquía",
  "Rusia",
  "China",
  "Japón",
  "Corea del Sur",
  "India",
  "Tailandia",
  "Vietnam",
  "Indonesia",
  "Filipinas",
  "Australia",
  "Nueva Zelanda",
  "Sudáfrica",
  "Egipto",
  "Marruecos",
  "Arabia Saudita",
  "Emiratos Árabes Unidos",
];
